{{- if .Values.rsync.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pv-migrate.fullname" . }}-rsync
  namespace: {{ .Values.rsync.namespace }}
  labels:
    app.kubernetes.io/component: rsync
    {{- include "pv-migrate.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.rsync.backoffLimit }}
  template:
    metadata:
      {{- with .Values.rsync.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: rsync
        {{- include "pv-migrate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.rsync.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pv-migrate.rsync.serviceAccountName" . }}
      restartPolicy: {{ .Values.rsync.restartPolicy }}
      securityContext:
        {{- toYaml .Values.rsync.podSecurityContext | nindent 8 }}
      containers:
        - name: rsync
          command:
            - sh
            - -c
            - |
              set -x
              n=0
              rc=1
              retries={{ .Values.rsync.maxRetries }}
              attempts=$((retries+1))
              period={{ .Values.rsync.retryPeriodSeconds }}
              {{ if .Values.rsync.privateKeyMount -}}
              privateKeyFilename=$(basename "{{ .Values.rsync.privateKeyMountPath }}")
              mkdir -p "$HOME/.ssh"
              chmod 700 "$HOME/.ssh"
              cp -v "{{ .Values.rsync.privateKeyMountPath }}" "$HOME/.ssh/"
              chmod 400 "$HOME/.ssh/$privateKeyFilename"
              {{- end }}
              while [ "$n" -le "$retries" ]
              do
                {{ required ".Values.rsync.command is required!" .Values.rsync.command }} {{ .Values.rsync.extraArgs }} && rc=0 && break
                n=$((n+1))
                echo "rsync attempt $n/$attempts failed, waiting $period seconds before trying again"
                sleep $period
              done

              if [ $rc -ne 0 ]; then
                echo "rsync job failed after $retries retries"
              fi
              exit $rc
          env:
            # Add fixed environment variables here
            - name: HTTP_PROXY
              value: "http://www-proxy.nl.ao-srv.com:8080"
            - name: HTTPS_PROXY
              value: "http://www-proxy.nl.ao-srv.com:8080"
            - name: NO_PROXY
              value: "NO_PROXY=127.0.0.1,161.89.22.251,localhost,DEFTHWA9C99SRV,DENBGAT9L9NSRV,DEFTHWA9A8USRV,DENBGAT9YP1SRV,DENBGAT95LXSRV,DEFTHWA91JLSRV,DENBGAT9MC8SRV,155.45.182.232,155.45.182.233,161.89.22.250,10.96.0.0/12,10.244.0.0/16,10.0.0.0/8,155.45.0.0/16,155.45.128.0/16,161.89.0.0/16,.saacon.net,.cluster.local,.svc"
            - name: http_proxy
              value: "http://www-proxy.nl.ao-srv.com:8080"
            - name: https_proxy
              value: "http://www-proxy.nl.ao-srv.com:8080"
            - name: no_proxy
              value: "no_proxy=127.0.0.1,161.89.22.251,localhost,DEFTHWA9C99SRV,DENBGAT9L9NSRV,DEFTHWA9A8USRV,DENBGAT9YP1SRV,DENBGAT95LXSRV,DEFTHWA91JLSRV,DENBGAT9MC8SRV,155.45.182.232,155.45.182.233,161.89.22.250,10.96.0.0/12,10.244.0.0/16,10.0.0.0/8,155.45.0.0/16,155.45.128.0/16,161.89.0.0/16,.saacon.net,.cluster.local,.svc"
          securityContext:
            {{- toYaml .Values.rsync.securityContext | nindent 12 }}
          image: "{{ .Values.rsync.image.repository }}:{{ .Values.rsync.image.tag }}"
          imagePullPolicy: {{ .Values.rsync.image.pullPolicy }}
          resources:
            {{- toYaml .Values.rsync.resources | nindent 12 }}
          volumeMounts:
            {{- range $index, $mount := .Values.rsync.pvcMounts }}
            - mountPath: {{ $mount.mountPath }}
              name: vol-{{ $index }}
              readOnly: {{ default false $mount.readOnly }}
            {{- end }}
            {{- if .Values.rsync.privateKeyMount }}
            - mountPath: {{ .Values.rsync.privateKeyMountPath }}
              name: private-key
              subPath: privateKey
            {{- end }}
      nodeName: {{ .Values.rsync.nodeName }}
      {{- with .Values.rsync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rsync.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rsync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostAliases:
        {{- if .Values.rsync.hostAliases }}
        {{- toYaml .Values.rsync.hostAliases | nindent 8 }}
        {{- end }}
      volumes:
        {{- range $index, $mount := .Values.rsync.pvcMounts }}
        - name: vol-{{ $index }}
          persistentVolumeClaim:
            claimName: {{ required ".Values.rsync.pvcMounts[*].pvcName is required!" $mount.name }}
            readOnly: {{ default false $mount.readOnly }}
        {{- end }}
        {{- if .Values.rsync.privateKeyMount }}
        - name: private-key
          secret:
            secretName: {{ include "pv-migrate.fullname" . }}-rsync
            defaultMode: 0400
        {{- end }}
{{- end }}
