---
name: build
on:
  push:
    branches: [master, renovate/**]
    paths-ignore:
      - '**.md'
      - img/**
      - test/**
      - .gitignore
      - docker/**
      - helm/**
      - renovate.json
      - .krew.yaml
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - img/**
      - test/**
      - .gitignore
      - docker/**
      - helm/**
      - renovate.json
      - .krew.yaml
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Install go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          # renovate: depName=go-task/task datasource=github-releases
          version: 3.39.2
      - name: Tidy go.mod
        run: go mod tidy
      - name: Run linters
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          # renovate: depName=golangci/golangci-lint datasource=github-releases
          version: v1.61.0
          args: --timeout=10m0s
          install-mode: goinstall
      - name: Build with Goreleaser
        if: ${{ always() }}
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v2.3.2
          args: build --snapshot --clean --single-target
      - name: Update usage
        run: task update-usage
      - name: Check for dirty files
        run: git diff --exit-code
